apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ctam
  name: ctamlocal-db
spec:
  selector:
    matchLabels:
      app: ctamlocal-db
  replicas: 1
  template:
    metadata:
      labels:
        app: ctamlocal-db
    spec:
      containers:
        - name: ctamlocaldb
          image: postgres:15
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: POSTGRES_PASSWORD
              value: docker
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: local-api-database
      restartPolicy: Always
      volumes:
          - name: local-api-database
            persistentVolumeClaim:
              claimName: local-api-database
  strategy:
    type: Recreate
  paused: false
