version: '3.4'

services:

  ctamclouddb:
    container_name: ctamclouddb
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - cloud-api-database:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=C@ptur3T
    ports:
      - 1433:1433

  ctamcloudapi:
    container_name: ctamcloudapi
    image: ctrdeuwctamdevcontregistry.azurecr.io/ctamcloudapi
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      TENANT_CONNECTION: '{"ct": "Server=ctamclouddb;Database=ctam;User ID=sa;Password=C@ptur3T;Application Name=Politie.CloudAPI;TrustServerCertificate=True;"}'
      UseAzureAppConfig: 'false'
    ports:
      - 5001:80
    depends_on:
      - ctamclouddb
    # This entrypoint waits until database responds before running ctamcloudapi and uses a timeout of 30 seconds
    entrypoint: ["./wait-for-it.sh", "ctamclouddb:1433", "-t", "30" , "--", "dotnet","CloudAPI.dll"]
    # remove 'entrypoint' above if development is done for multi-tenants
    # however keep in mind that the ASPNETCORE_ENVIRONMENT loads the appsettings.docker.json
    # where connectionstring is set and used in runtime for initializing the db.

  ctamcloudui:
    container_name: ctamcloudui
    image: ctrdeuwctamdevcontregistry.azurecr.io/ctamcloudui
    ports:
      - 8080:80

  ctamlocaldb:
    container_name: ctamlocaldb
    environment:
      ACCEPT_EULA: "Y"
      POSTGRES_PASSWORD: docker
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
    - "local-api-database:/var/lib/postgresql/data"

  ctamlocalapi-one:
    container_name: ctamlocalapi-one
    depends_on:
      - ctamlocaldb
    environment:
      TENANT_ID: ct
      ASPNETCORE_ENVIRONMENT: DockerLocal
      "CloudAPI:CabinetAPIKey" : "0Ab70SY6speWLaLICyiyxHZ6efIJJ"
      "CloudAPI:APIBaseUrl" : "http://host.docker.internal:5001"
      "CloudAPI:SignalRUrl" : "http://host.docker.internal:5001/events"
      "HardwareAPI:APIBaseUrl" : "http://host.docker.internal:8001"
      "ConnectionStrings:Database" : "Host=ctamlocaldb;Port=5432;Username=postgres;Password=docker;Database=ctam-local-one"
    image: ctrdeuwctamdevcontregistry.azurecr.io/ctamlocalapi
    ports:
      - "6001:80"
    
  ctamlocalapi-two:
    container_name: ctamlocalapi-two
    depends_on:
      - ctamlocaldb
    environment:
      TENANT_ID: ct
      ASPNETCORE_ENVIRONMENT: DockerLocal
      "CloudAPI:CabinetAPIKey" : "0Ab70SY6speWLaLICyiyxHZ6efIJJ"
      "CloudAPI:APIBaseUrl" : "http://host.docker.internal:5001/"
      "CloudAPI:SignalRUrl" : "http://host.docker.internal:5001/events"
      "HardwareAPI:APIBaseUrl" : "http://host.docker.internal:8002"
      "ConnectionStrings:Database" : "Host=ctamlocaldb;Port=5432;Username=postgres;Password=docker;Database=ctam-local-two"
    image: ctrdeuwctamdevcontregistry.azurecr.io/ctamlocalapi
    ports:
      - "6002:80"
    
  ctamlocalapi-three:
    container_name: ctamlocalapi-three
    depends_on:
      - ctamlocaldb
    environment:
      TENANT_ID: ct
      ASPNETCORE_ENVIRONMENT: DockerLocal
      "CloudAPI:CabinetAPIKey" : "0Ab70SY6speWLaLICyiyxHZ6efIJJ"
      "CloudAPI:APIBaseUrl" : "http://host.docker.internal:5001/"
      "CloudAPI:SignalRUrl" : "http://host.docker.internal:5001/events"
      "HardwareAPI:APIBaseUrl" : "http://host.docker.internal:8003"
      "ConnectionStrings:Database" : "Host=ctamlocaldb;Port=5432;Username=postgres;Password=docker;Database=ctam-local-three"
    image: ctrdeuwctamdevcontregistry.azurecr.io/ctamlocalapi
    ports:
      - "6003:80"
    
  ctamhardwareapi-one:
    container_name: ctamhardwareapi-one
    depends_on:
      - ctamlocaldb
      - ctamlocalapi-one
    environment:
      ASPNETCORE_ENVIRONMENT: DockerLocal
      "LocalAPI:Url" : "http://host.docker.internal:6001/local-events"
      "LocalAPI:CloudUrl" : "http://host.docker.internal:6001/local-events"
    image: ctrdeuwctamdevcontregistry.azurecr.io/ctamhardwareapi
    ports:
      - "8001:80"

  ctamhardwareapi-two:
    container_name: ctamhardwareapi-two
    depends_on:
      - ctamlocaldb
      - ctamlocalapi-two
    environment:
      ASPNETCORE_ENVIRONMENT: DockerLocal
      "LocalAPI:Url" : "http://host.docker.internal:6002/local-events"
      "LocalAPI:CloudUrl" : "http://host.docker.internal:6002/local-events"
    image: ctrdeuwctamdevcontregistry.azurecr.io/ctamhardwareapi
    ports:
      - "8002:80"

  ctamhardwareapi-three:
    container_name: ctamhardwareapi-three
    depends_on:
      - ctamlocaldb
      - ctamlocalapi-three
    environment:
      ASPNETCORE_ENVIRONMENT: DockerLocal
      "LocalAPI:Url" : "http://host.docker.internal:6003/local-events"
      "LocalAPI:CloudUrl" : "http://host.docker.internal:6003/local-events"
    image: ctrdeuwctamdevcontregistry.azurecr.io/ctamhardwareapi
    ports:
      - "8003:80"

  ctamlocalui-one:
    container_name: ctamlocalui-one
    environment:
      REST_API_URL_REPLACE : "http://localhost:6001"
    image: ctrdeuwctamdevcontregistry.azurecr.io/ctamlocalui
    ports:
      - 8081:80

  ctamlocalui-two:
    container_name: ctamlocalui-two
    environment:
      REST_API_URL_REPLACE : "http://localhost:6002"
    image: ctrdeuwctamdevcontregistry.azurecr.io/ctamlocalui
    ports:
      - 8082:80
  
  ctamlocalui-three:
    container_name: ctamlocalui-three
    environment:
      REST_API_URL_REPLACE : "http://localhost:6003"
    image: ctrdeuwctamdevcontregistry.azurecr.io/ctamlocalui
    ports:
      - 8083:80

volumes:
  cloud-api-database: {}
  local-api-database: {}