version: '3.4'

services:

  cloud1:
    container_name: c1
    image: cloudapi-local
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      CONNECTION_STRING: "Server=database,1433;Database=ctam;User ID=sa;Password=C@ptur3T;Application Name=Politie.CloudAPI"
      TENANT_CONNECTION: '{"ct":"Server=database;Database=ctam;User ID=sa;Password=C@ptur3T;Application Name=Politie.CloudAPI"}'
      ID: cloud-api1
    ports:
      - 9000:80
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./logs:/app/logs
    restart: always

  cloud2:
    container_name: c2
    image: cloudapi-local
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      CONNECTION_STRING: "Server=database,1433;Database=ctam;User ID=sa;Password=C@ptur3T;Application Name=Politie.CloudAPI"
      TENANT_CONNECTION: '{"ct":"Server=database;Database=ctam;User ID=sa;Password=C@ptur3T;Application Name=Politie.CloudAPI"}'
      ID: cloud-api2
    ports:
      - 9001:80
    depends_on:
      - database
    links:
      - database
    restart: always

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "C@ptur3T"
    volumes:
      - ctam-docker-database:/var/opt/mssql


volumes:
  ctam-docker-database: {}
